
import java.sql.*;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Akash
 */
public class Booking_Page2 extends javax.swing.JFrame {
    
        String location="";
        int np=0;

    /**
     * Creates new form Booking_Page2
     */
    public Booking_Page2() {
        initComponents();
    }
    class Options
    {
        String get_name()
        {
           String movie_name="";
        try {                                                                   //connection started
                Class.forName("java.sql.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/Bookmyshow","root","root");
                Statement stmt=con.createStatement();
                String query="SELECT Movie_Name FROM SUBMISSION;";              //query to get movie name from table selected_movie
                ResultSet rs=stmt.executeQuery(query);
                while(rs.next())  
                {
                movie_name=rs.getString("Movie_Name");
                }               
                rs.close();  
                stmt.close();
                con.close();
        }
        catch(ClassNotFoundException | SQLException e) {
            {
                JOptionPane.showMessageDialog(null,e);
            }
        } 
        return movie_name;
        }
        void times(String S){
            times.removeAllItems();;
            times.addItem("Pick One");
            String time=S+",";
            String t="";
            int l=time.length();
            for(int i=0;i<l;i++)
            {
                char z=time.charAt(i);
                if(z==','){
                    times.addItem(t);
                    t="";
                }
                else{
                    t=t+z;
                }
            }
        }
        void dates(int d){
            int dat=d;
            int f=d+7;
            for(int i=d;i<=f;i++){
                System.out.println(i);
            mv_date.addItem(i);
        }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        header = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        venues = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        t1 = new javax.swing.JLabel();
        result = new javax.swing.JLabel();
        times = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        g_price = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        Gold = new javax.swing.JPanel();
        G1 = new javax.swing.JRadioButton();
        G2 = new javax.swing.JRadioButton();
        G3 = new javax.swing.JRadioButton();
        G4 = new javax.swing.JRadioButton();
        G5 = new javax.swing.JRadioButton();
        G6 = new javax.swing.JRadioButton();
        G7 = new javax.swing.JRadioButton();
        G8 = new javax.swing.JRadioButton();
        G9 = new javax.swing.JRadioButton();
        G10 = new javax.swing.JRadioButton();
        G11 = new javax.swing.JRadioButton();
        G12 = new javax.swing.JRadioButton();
        G13 = new javax.swing.JRadioButton();
        G14 = new javax.swing.JRadioButton();
        G15 = new javax.swing.JRadioButton();
        G16 = new javax.swing.JRadioButton();
        G17 = new javax.swing.JRadioButton();
        G18 = new javax.swing.JRadioButton();
        G19 = new javax.swing.JRadioButton();
        G20 = new javax.swing.JRadioButton();
        G21 = new javax.swing.JRadioButton();
        G22 = new javax.swing.JRadioButton();
        G23 = new javax.swing.JRadioButton();
        G24 = new javax.swing.JRadioButton();
        Silver = new javax.swing.JPanel();
        S1 = new javax.swing.JRadioButton();
        S2 = new javax.swing.JRadioButton();
        S3 = new javax.swing.JRadioButton();
        S4 = new javax.swing.JRadioButton();
        S5 = new javax.swing.JRadioButton();
        S6 = new javax.swing.JRadioButton();
        S7 = new javax.swing.JRadioButton();
        S8 = new javax.swing.JRadioButton();
        S9 = new javax.swing.JRadioButton();
        S10 = new javax.swing.JRadioButton();
        S11 = new javax.swing.JRadioButton();
        S12 = new javax.swing.JRadioButton();
        S13 = new javax.swing.JRadioButton();
        S14 = new javax.swing.JRadioButton();
        S15 = new javax.swing.JRadioButton();
        S16 = new javax.swing.JRadioButton();
        S17 = new javax.swing.JRadioButton();
        S18 = new javax.swing.JRadioButton();
        S19 = new javax.swing.JRadioButton();
        S20 = new javax.swing.JRadioButton();
        S21 = new javax.swing.JRadioButton();
        S22 = new javax.swing.JRadioButton();
        S23 = new javax.swing.JRadioButton();
        S24 = new javax.swing.JRadioButton();
        Bronze = new javax.swing.JPanel();
        B1 = new javax.swing.JRadioButton();
        B2 = new javax.swing.JRadioButton();
        B3 = new javax.swing.JRadioButton();
        B4 = new javax.swing.JRadioButton();
        B5 = new javax.swing.JRadioButton();
        B6 = new javax.swing.JRadioButton();
        B7 = new javax.swing.JRadioButton();
        B8 = new javax.swing.JRadioButton();
        B9 = new javax.swing.JRadioButton();
        B10 = new javax.swing.JRadioButton();
        B11 = new javax.swing.JRadioButton();
        B12 = new javax.swing.JRadioButton();
        B13 = new javax.swing.JRadioButton();
        B14 = new javax.swing.JRadioButton();
        B15 = new javax.swing.JRadioButton();
        B16 = new javax.swing.JRadioButton();
        B17 = new javax.swing.JRadioButton();
        B18 = new javax.swing.JRadioButton();
        B19 = new javax.swing.JRadioButton();
        B20 = new javax.swing.JRadioButton();
        B21 = new javax.swing.JRadioButton();
        B22 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        mv_date = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        s_price = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        b_price = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new ImageIcon("icon.png").getImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "[UserName]", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(153, 0, 0))); // NOI18N

        jButton4.setForeground(new java.awt.Color(153, 0, 0));
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setForeground(new java.awt.Color(153, 0, 0));
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Pick Your Place:");

        venues.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Venue" }));
        venues.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                venuesItemStateChanged(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Next");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        result.setForeground(new java.awt.Color(0, 102, 0));
        result.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        times.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pick One" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 0));
        jLabel4.setText("Show Times:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 0));
        jLabel6.setText("Ticket Price:");

        g_price.setEditable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pick Your Seats", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 0, 0))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(153, 0, 0));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
        });

        Gold.setBackground(new java.awt.Color(204, 153, 0));

        G1.setBackground(new java.awt.Color(204, 153, 0));

        G2.setBackground(new java.awt.Color(204, 153, 0));

        G3.setBackground(new java.awt.Color(204, 153, 0));

        G4.setBackground(new java.awt.Color(204, 153, 0));

        G5.setBackground(new java.awt.Color(204, 153, 0));

        G6.setBackground(new java.awt.Color(204, 153, 0));

        G7.setBackground(new java.awt.Color(204, 153, 0));

        G8.setBackground(new java.awt.Color(204, 153, 0));

        G9.setBackground(new java.awt.Color(204, 153, 0));

        G10.setBackground(new java.awt.Color(204, 153, 0));

        G11.setBackground(new java.awt.Color(204, 153, 0));

        G12.setBackground(new java.awt.Color(204, 153, 0));
        G12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G12ActionPerformed(evt);
            }
        });

        G13.setBackground(new java.awt.Color(204, 153, 0));

        G14.setBackground(new java.awt.Color(204, 153, 0));

        G15.setBackground(new java.awt.Color(204, 153, 0));

        G16.setBackground(new java.awt.Color(204, 153, 0));

        G17.setBackground(new java.awt.Color(204, 153, 0));

        G18.setBackground(new java.awt.Color(204, 153, 0));

        G19.setBackground(new java.awt.Color(204, 153, 0));

        G20.setBackground(new java.awt.Color(204, 153, 0));

        G21.setBackground(new java.awt.Color(204, 153, 0));

        G22.setBackground(new java.awt.Color(204, 153, 0));

        G23.setBackground(new java.awt.Color(204, 153, 0));

        G24.setBackground(new java.awt.Color(204, 153, 0));

        javax.swing.GroupLayout GoldLayout = new javax.swing.GroupLayout(Gold);
        Gold.setLayout(GoldLayout);
        GoldLayout.setHorizontalGroup(
            GoldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GoldLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GoldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(G1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(G2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GoldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(G4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(G3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GoldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(G5)
                    .addComponent(G6))
                .addGap(42, 42, 42)
                .addGroup(GoldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(G7)
                    .addComponent(G8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GoldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(G9)
                    .addComponent(G10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GoldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(G11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(G12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GoldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(G13)
                    .addComponent(G14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GoldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(G15)
                    .addComponent(G16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GoldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(G17)
                    .addComponent(G18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(GoldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(G19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(G20, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GoldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(G21)
                    .addComponent(G22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GoldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(G23, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G24, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        GoldLayout.setVerticalGroup(
            GoldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GoldLayout.createSequentialGroup()
                .addComponent(G17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(G18))
            .addGroup(GoldLayout.createSequentialGroup()
                .addComponent(G15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(G16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GoldLayout.createSequentialGroup()
                .addComponent(G5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(G6))
            .addGroup(GoldLayout.createSequentialGroup()
                .addComponent(G3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(G4))
            .addGroup(GoldLayout.createSequentialGroup()
                .addComponent(G1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(G2))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GoldLayout.createSequentialGroup()
                .addComponent(G13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(G14))
            .addGroup(GoldLayout.createSequentialGroup()
                .addComponent(G11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(G12))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GoldLayout.createSequentialGroup()
                .addComponent(G23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(G24))
            .addGroup(GoldLayout.createSequentialGroup()
                .addComponent(G21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(G22))
            .addGroup(GoldLayout.createSequentialGroup()
                .addComponent(G19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(G20))
            .addGroup(GoldLayout.createSequentialGroup()
                .addComponent(G7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(G8))
            .addGroup(GoldLayout.createSequentialGroup()
                .addComponent(G9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(G10))
        );

        Silver.setBackground(new java.awt.Color(153, 153, 153));

        S1.setBackground(new java.awt.Color(153, 153, 153));

        S2.setBackground(new java.awt.Color(153, 153, 153));

        S3.setBackground(new java.awt.Color(153, 153, 153));

        S4.setBackground(new java.awt.Color(153, 153, 153));

        S5.setBackground(new java.awt.Color(153, 153, 153));

        S6.setBackground(new java.awt.Color(153, 153, 153));

        S7.setBackground(new java.awt.Color(153, 153, 153));

        S8.setBackground(new java.awt.Color(153, 153, 153));

        S9.setBackground(new java.awt.Color(153, 153, 153));

        S10.setBackground(new java.awt.Color(153, 153, 153));

        S11.setBackground(new java.awt.Color(153, 153, 153));

        S12.setBackground(new java.awt.Color(153, 153, 153));
        S12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S12ActionPerformed(evt);
            }
        });

        S13.setBackground(new java.awt.Color(153, 153, 153));

        S14.setBackground(new java.awt.Color(153, 153, 153));

        S15.setBackground(new java.awt.Color(153, 153, 153));

        S16.setBackground(new java.awt.Color(153, 153, 153));

        S17.setBackground(new java.awt.Color(153, 153, 153));

        S18.setBackground(new java.awt.Color(153, 153, 153));

        S19.setBackground(new java.awt.Color(153, 153, 153));

        S20.setBackground(new java.awt.Color(153, 153, 153));

        S21.setBackground(new java.awt.Color(153, 153, 153));

        S22.setBackground(new java.awt.Color(153, 153, 153));

        S23.setBackground(new java.awt.Color(153, 153, 153));

        S24.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout SilverLayout = new javax.swing.GroupLayout(Silver);
        Silver.setLayout(SilverLayout);
        SilverLayout.setHorizontalGroup(
            SilverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SilverLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SilverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(S1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(S2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SilverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(S4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(S3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SilverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(S5)
                    .addComponent(S6))
                .addGap(42, 42, 42)
                .addGroup(SilverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(S7)
                    .addComponent(S8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SilverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(S9)
                    .addComponent(S10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SilverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(S11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(S12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SilverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(S13)
                    .addComponent(S14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SilverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(S15)
                    .addComponent(S16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SilverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(S17)
                    .addComponent(S18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SilverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(S19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(S20, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SilverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(S21)
                    .addComponent(S22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SilverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(S23, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(S24, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        SilverLayout.setVerticalGroup(
            SilverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SilverLayout.createSequentialGroup()
                .addComponent(S17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(S18))
            .addGroup(SilverLayout.createSequentialGroup()
                .addComponent(S15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(S16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SilverLayout.createSequentialGroup()
                .addComponent(S5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(S6))
            .addGroup(SilverLayout.createSequentialGroup()
                .addComponent(S3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(S4))
            .addGroup(SilverLayout.createSequentialGroup()
                .addComponent(S1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(S2))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SilverLayout.createSequentialGroup()
                .addComponent(S13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(S14))
            .addGroup(SilverLayout.createSequentialGroup()
                .addComponent(S11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(S12))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SilverLayout.createSequentialGroup()
                .addComponent(S23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(S24))
            .addGroup(SilverLayout.createSequentialGroup()
                .addComponent(S21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(S22))
            .addGroup(SilverLayout.createSequentialGroup()
                .addComponent(S19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(S20))
            .addGroup(SilverLayout.createSequentialGroup()
                .addComponent(S7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(S8))
            .addGroup(SilverLayout.createSequentialGroup()
                .addComponent(S9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(S10))
        );

        Bronze.setBackground(new java.awt.Color(153, 51, 0));

        B1.setBackground(new java.awt.Color(153, 51, 0));

        B2.setBackground(new java.awt.Color(153, 51, 0));

        B3.setBackground(new java.awt.Color(153, 51, 0));

        B4.setBackground(new java.awt.Color(153, 51, 0));

        B5.setBackground(new java.awt.Color(153, 51, 0));

        B6.setBackground(new java.awt.Color(153, 51, 0));

        B7.setBackground(new java.awt.Color(153, 51, 0));

        B8.setBackground(new java.awt.Color(153, 51, 0));

        B9.setBackground(new java.awt.Color(153, 51, 0));

        B10.setBackground(new java.awt.Color(153, 51, 0));

        B11.setBackground(new java.awt.Color(153, 51, 0));
        B11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B11ActionPerformed(evt);
            }
        });

        B12.setBackground(new java.awt.Color(153, 51, 0));

        B13.setBackground(new java.awt.Color(153, 51, 0));

        B14.setBackground(new java.awt.Color(153, 51, 0));

        B15.setBackground(new java.awt.Color(153, 51, 0));

        B16.setBackground(new java.awt.Color(153, 51, 0));

        B17.setBackground(new java.awt.Color(153, 51, 0));

        B18.setBackground(new java.awt.Color(153, 51, 0));

        B19.setBackground(new java.awt.Color(153, 51, 0));

        B20.setBackground(new java.awt.Color(153, 51, 0));

        B21.setBackground(new java.awt.Color(153, 51, 0));

        B22.setBackground(new java.awt.Color(153, 51, 0));

        javax.swing.GroupLayout BronzeLayout = new javax.swing.GroupLayout(Bronze);
        Bronze.setLayout(BronzeLayout);
        BronzeLayout.setHorizontalGroup(
            BronzeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BronzeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BronzeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(B1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BronzeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(B4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BronzeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B5)
                    .addComponent(B6))
                .addGap(42, 42, 42)
                .addComponent(B7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BronzeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B8)
                    .addComponent(B9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BronzeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(B10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BronzeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B12)
                    .addComponent(B13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BronzeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B14)
                    .addComponent(B15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(BronzeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(B17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B18, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BronzeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B19)
                    .addComponent(B20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BronzeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B21, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B22, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        BronzeLayout.setVerticalGroup(
            BronzeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BronzeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BronzeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B16)
                    .addGroup(BronzeLayout.createSequentialGroup()
                        .addComponent(B14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(B15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BronzeLayout.createSequentialGroup()
                        .addComponent(B5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(B6))
                    .addGroup(BronzeLayout.createSequentialGroup()
                        .addComponent(B3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(B4))
                    .addGroup(BronzeLayout.createSequentialGroup()
                        .addComponent(B1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(B2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BronzeLayout.createSequentialGroup()
                        .addComponent(B12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(B13))
                    .addGroup(BronzeLayout.createSequentialGroup()
                        .addComponent(B10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(B11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BronzeLayout.createSequentialGroup()
                        .addComponent(B21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(B22))
                    .addGroup(BronzeLayout.createSequentialGroup()
                        .addComponent(B19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(B20))
                    .addGroup(BronzeLayout.createSequentialGroup()
                        .addComponent(B17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(B18))
                    .addComponent(B7)
                    .addGroup(BronzeLayout.createSequentialGroup()
                        .addComponent(B8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(B9)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bronze, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Gold, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Silver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Gold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Silver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bronze, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 0));
        jLabel5.setText("Pick A Date:");

        jLabel2.setText("G");

        s_price.setEditable(false);

        jLabel3.setText("S");

        b_price.setEditable(false);

        jLabel7.setText("B");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(venues, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(t1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(g_price, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(s_price, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(b_price, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(mv_date, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(times, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4))))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venues, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(times, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mv_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(g_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(s_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(b_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jButton1)
                        .addGap(49, 49, 49)
                        .addComponent(t1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jButton3)
                    .addComponent(jButton4)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // back to login
        Booking_Page1 obj=new Booking_Page1();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // exit code
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //onload
        try {
                Class.forName("java.sql.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/Bookmyshow","root","root");
                Statement stmt=con.createStatement();
                String query="SELECT * FROM USERLOCATION WHERE Id=1;";          //Making the query
                ResultSet rs=stmt.executeQuery(query);
                while(rs.next())
                {
                    location=rs.getString("Location");
                }
            }
            catch(ClassNotFoundException | SQLException e) {
                JOptionPane.showMessageDialog(null,e);
            }
        try {
                Class.forName("java.sql.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/Bookmyshow","root","root");
                Statement stmt=con.createStatement();
                String query="SELECT * FROM USERNAME WHERE Id=1;";              //Making the query
                ResultSet rs=stmt.executeQuery(query);
                while(rs.next())
                {
                    String name=rs.getString("Name");
                    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "["+name+"]", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(153, 0, 0))); // NOI18N
                }
            }
            catch(ClassNotFoundException | SQLException e) {
                JOptionPane.showMessageDialog(null,e);
            }
        //nesting
        Options obj=new Options();
        String movie_name=obj.get_name();     
        try{
            Connection con1=DriverManager.getConnection("jdbc:mysql://localhost:3306/Bookmyshow","root","root");
            Statement stmt1=con1.createStatement();
            String query1="SELECT * FROM MOVIE_DATABASE WHERE Movie_Name='"+movie_name+"' AND Location='"+location+"';";
            ResultSet rs1=stmt1.executeQuery(query1);
            while(rs1.next())
            {
                String name1=rs1.getString("Hall");
                venues.addItem(name1);
            }
                rs1.close();  
                stmt1.close();
                con1.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        //date
        try{
            Connection con1=DriverManager.getConnection("jdbc:mysql://localhost:3306/Bookmyshow","root","root");
            Statement stmt1=con1.createStatement();
            String query="SELECT CURDATE();";
            ResultSet rs1=stmt1.executeQuery(query);
            while(rs1.next())
            {
                String Date=rs1.getString("curdate()");
                String query1="SELECT DAYOFMONTH('"+Date+"');";
                ResultSet rs2=stmt1.executeQuery(query1);
                while(rs2.next()){
                    int Day=rs2.getInt("DAYOFMONTH('"+Date+"')");
                    System.out.println(Day);
                    obj.dates(Day);
                }
            }
        }
        catch(Exception e){
            
        }
    }//GEN-LAST:event_formWindowOpened

    private void venuesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_venuesItemStateChanged
        // getting everything
        Options obj=new Options();
        String movie_name=obj.get_name();
        try{
            String venue=(String)venues.getSelectedItem();
            Connection con1=DriverManager.getConnection("jdbc:mysql://localhost:3306/Bookmyshow","root","root");
            Statement stmt1=con1.createStatement();
            String query="SELECT * FROM MOVIE_DATABASE WHERE Movie_Name='"+movie_name+"' AND Hall='"+venue+"' AND Location='"+location+"';";
            ResultSet rs1=stmt1.executeQuery(query);
            while(rs1.next())
            {
                String shows=rs1.getString("Timings");
                obj.times(shows);
                b_price.setText(rs1.getInt("G_Price")+"");
                s_price.setText(rs1.getInt("S_Price")+"");
                g_price.setText(rs1.getInt("B_Price")+"");
            }
                rs1.close();  
                stmt1.close();
                con1.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_venuesItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // reset button
        venues.setSelectedIndex(0);
        times.setSelectedIndex(0);
            G1.setSelected(false);
            G2.setSelected(false);
            G3.setSelected(false);
            S4.setSelected(false);
            G5.setSelected(false);
            G6.setSelected(false);
            G7.setSelected(false);
            G8.setSelected(false);
            G9.setSelected(false);
            G10.setSelected(false);
            G12.setSelected(false);
            G17.setSelected(false);
            G18.setSelected(false);
            G19.setSelected(false);
            G20.setSelected(false);
            G21.setSelected(false);
            G22.setSelected(false);
            G23.setSelected(false);
            G24.setSelected(false);
            S1.setSelected(false);
            S2.setSelected(false);
            S3.setSelected(false);
            S4.setSelected(false);
            S6.setSelected(false);
            S7.setSelected(false);
            S8.setSelected(false);
            S9.setSelected(false);
            S10.setSelected(false);
            S12.setSelected(false);
            S17.setSelected(false);
            S18.setSelected(false);
            S19.setSelected(false);
            S20.setSelected(false);
            S21.setSelected(false);
            S22.setSelected(false);
            S23.setSelected(false);
            S24.setSelected(false);
            B1.setSelected(false);
            B2.setSelected(false);
            B3.setSelected(false);
            B4.setSelected(false);
            B6.setSelected(false);
            B7.setSelected(false);
            B8.setSelected(false);
            B9.setSelected(false);
            B10.setSelected(false);
            B12.setSelected(false);
            B17.setSelected(false);
            B18.setSelected(false);
            B19.setSelected(false);
            B20.setSelected(false);
            B21.setSelected(false);
            B22.setSelected(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void G12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_G12ActionPerformed

    private void S12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_S12ActionPerformed

    private void B11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B11ActionPerformed

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
        //checking seats
        int a=0;
        if(G1.isSelected()==true){
            a++;
        }
        if(G2.isSelected()==true){
            a++;
        }
        if(G3.isSelected()==true){
            a++;
        }
        if(G4.isSelected()==true){
            a++;
        }
        if(G5.isSelected()==true){
            a++;
        }
        if(G6.isSelected()==true){
            a++;
        }
        if(G7.isSelected()==true){
            a++;
        }
        if(G8.isSelected()==true){
            a++;
        }
        if(G9.isSelected()==true){
            a++;
        }
        if(G10.isSelected()==true){
            a++;
        }
        if(G11.isSelected()==true){
            a++;
        }
        if(G12.isSelected()==true){
            a++;
        }
        if(G13.isSelected()==true){
            a++;
        }
        if(G14.isSelected()==true){
            a++;
        }
        if(G15.isSelected()==true){
            a++;
        }
        if(G16.isSelected()==true){
            a++;
        }
        if(G17.isSelected()==true){
            a++;
        }
        if(G18.isSelected()==true){
            a++;
        }
        if(G19.isSelected()==true){
            a++;
        }
        if(G20.isSelected()==true){
            a++;
        }
        if(G21.isSelected()==true){
            a++;
        }
        if(G22.isSelected()==true){
            a++;
        }
        if(G23.isSelected()==true){
            a++;
        }
        if(G24.isSelected()==true){
            a++;
        }
        if(S1.isSelected()==true){
            a++;
        }
        if(S2.isSelected()==true){
            a++;
        }
        if(S3.isSelected()==true){
            a++;
        }
        if(S4.isSelected()==true){
            a++;
        }
        if(S5.isSelected()==true){
            a++;
        }
        if(S6.isSelected()==true){
            a++;
        }
        if(S7.isSelected()==true){
            a++;
        }
        if(S8.isSelected()==true){
            a++;
        }
        if(S9.isSelected()==true){
            a++;
        }
        if(S10.isSelected()==true){
            a++;
        }
        if(S11.isSelected()==true){
            a++;
        }
        if(S12.isSelected()==true){
            a++;
        }
        if(S13.isSelected()==true){
            a++;
        }
        if(S14.isSelected()==true){
            a++;
        }
        if(S15.isSelected()==true){
            a++;
        }
        if(S16.isSelected()==true){
            a++;
        }
        if(S17.isSelected()==true){
            a++;
        }
        if(S18.isSelected()==true){
            a++;
        }
        if(S19.isSelected()==true){
            a++;
        }
        if(S20.isSelected()==true){
            a++;
        }
        if(S21.isSelected()==true){
            a++;
        }
        if(S22.isSelected()==true){
            a++;
        }
        if(S23.isSelected()==true){
            a++;
        }
        if(S24.isSelected()==true){
            a++;
        }
        if(B1.isSelected()==true){
            a++;
        }
        if(B2.isSelected()==true){
            a++;
        }
        if(B3.isSelected()==true){
            a++;
        }
        if(B4.isSelected()==true){
            a++;
        }
        if(B5.isSelected()==true){
            a++;
        }
        if(B6.isSelected()==true){
            a++;
        }
        if(B7.isSelected()==true){
            a++;
        }
        if(B8.isSelected()==true){
            a++;
        }
        if(B9.isSelected()==true){
            a++;
        }
        if(B10.isSelected()==true){
            a++;
        }
        if(B11.isSelected()==true){
            a++;
        }
        if(B12.isSelected()==true){
            a++;
        }
        if(B13.isSelected()==true){
            a++;
        }
        if(B14.isSelected()==true){
            a++;
        }
        if(B15.isSelected()==true){
            a++;
        }
        if(B16.isSelected()==true){
            a++;
        }
        if(B17.isSelected()==true){
            a++;
        }
        if(B18.isSelected()==true){
            a++;
        }
        if(B19.isSelected()==true){
            a++;
        }
        if(B20.isSelected()==true){
            a++;
        }
        if(B21.isSelected()==true){
            a++;
        }
        if(B22.isSelected()==true){
            a++;
        }
        np=a;
    }//GEN-LAST:event_jPanel2MouseEntered

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here
        String venue=(String)venues.getSelectedItem();
        if(venue.equals("Venues"))
        {
            JOptionPane.showMessageDialog(null, "Please select a venue!");
        }
        else {
            int seats=np;
            String time=(String)times.getSelectedItem();
            int G_price=Integer.parseInt(g_price.getText())*seats;
            int S_price=Integer.parseInt(s_price.getText())*seats;
            int B_price=Integer.parseInt(b_price.getText())*seats;
            int total_price=G_price+S_price+B_price;
            try{
                Class.forName("java.sql.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/Bookmyshow","root","root");
                Statement stmt=con.createStatement();
                String query="UPDATE SUBMISSION SET Venue='"+venue+"' WHERE Id=1;";
                String query1="UPDATE SUBMISSION SET Seats='"+seats+"' WHERE Id=1;";
                String query3="UPDATE SUBMISSION SET Total_Price='"+total_price+"' WHERE Id=1;";
                String query4="UPDATE SUBMISSION SET Timing='"+time+"' WHERE Id=1;";
                String query5="UPDATE SUBMISSION SET Date='"+(int)mv_date.getSelectedItem()+"' WHERE Id=1;";
                stmt.executeUpdate(query);
                stmt.executeUpdate(query1);
                stmt.executeUpdate(query3);
                stmt.executeUpdate(query4);
                stmt.executeUpdate(query5);
                stmt.close();
                con.close();
                Payment obj=new Payment();
                obj.setVisible(true);
                this.setVisible(false);
            }
            catch(ClassNotFoundException | SQLException e)                      //catching error
            {
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Booking_Page2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Booking_Page2().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton B1;
    private javax.swing.JRadioButton B10;
    private javax.swing.JRadioButton B11;
    private javax.swing.JRadioButton B12;
    private javax.swing.JRadioButton B13;
    private javax.swing.JRadioButton B14;
    private javax.swing.JRadioButton B15;
    private javax.swing.JRadioButton B16;
    private javax.swing.JRadioButton B17;
    private javax.swing.JRadioButton B18;
    private javax.swing.JRadioButton B19;
    private javax.swing.JRadioButton B2;
    private javax.swing.JRadioButton B20;
    private javax.swing.JRadioButton B21;
    private javax.swing.JRadioButton B22;
    private javax.swing.JRadioButton B3;
    private javax.swing.JRadioButton B4;
    private javax.swing.JRadioButton B5;
    private javax.swing.JRadioButton B6;
    private javax.swing.JRadioButton B7;
    private javax.swing.JRadioButton B8;
    private javax.swing.JRadioButton B9;
    private javax.swing.JPanel Bronze;
    private javax.swing.JRadioButton G1;
    private javax.swing.JRadioButton G10;
    private javax.swing.JRadioButton G11;
    private javax.swing.JRadioButton G12;
    private javax.swing.JRadioButton G13;
    private javax.swing.JRadioButton G14;
    private javax.swing.JRadioButton G15;
    private javax.swing.JRadioButton G16;
    private javax.swing.JRadioButton G17;
    private javax.swing.JRadioButton G18;
    private javax.swing.JRadioButton G19;
    private javax.swing.JRadioButton G2;
    private javax.swing.JRadioButton G20;
    private javax.swing.JRadioButton G21;
    private javax.swing.JRadioButton G22;
    private javax.swing.JRadioButton G23;
    private javax.swing.JRadioButton G24;
    private javax.swing.JRadioButton G3;
    private javax.swing.JRadioButton G4;
    private javax.swing.JRadioButton G5;
    private javax.swing.JRadioButton G6;
    private javax.swing.JRadioButton G7;
    private javax.swing.JRadioButton G8;
    private javax.swing.JRadioButton G9;
    private javax.swing.JPanel Gold;
    private javax.swing.JRadioButton S1;
    private javax.swing.JRadioButton S10;
    private javax.swing.JRadioButton S11;
    private javax.swing.JRadioButton S12;
    private javax.swing.JRadioButton S13;
    private javax.swing.JRadioButton S14;
    private javax.swing.JRadioButton S15;
    private javax.swing.JRadioButton S16;
    private javax.swing.JRadioButton S17;
    private javax.swing.JRadioButton S18;
    private javax.swing.JRadioButton S19;
    private javax.swing.JRadioButton S2;
    private javax.swing.JRadioButton S20;
    private javax.swing.JRadioButton S21;
    private javax.swing.JRadioButton S22;
    private javax.swing.JRadioButton S23;
    private javax.swing.JRadioButton S24;
    private javax.swing.JRadioButton S3;
    private javax.swing.JRadioButton S4;
    private javax.swing.JRadioButton S5;
    private javax.swing.JRadioButton S6;
    private javax.swing.JRadioButton S7;
    private javax.swing.JRadioButton S8;
    private javax.swing.JRadioButton S9;
    private javax.swing.JPanel Silver;
    private javax.swing.JTextField b_price;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField g_price;
    private javax.swing.JLabel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox mv_date;
    private javax.swing.JLabel result;
    private javax.swing.JTextField s_price;
    private javax.swing.JLabel t1;
    private javax.swing.JComboBox times;
    private javax.swing.JComboBox venues;
    // End of variables declaration//GEN-END:variables
}